# Generated by Django 3.2.7 on 2021-09-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_auth", "0004_auto_20160209_1902"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
