# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0004_auto_20170329_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='custom_iiif_manifest_url',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
