# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0005_auto_20180419_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='custom_iiif_canvas_id',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
