# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-14 19:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0007_auto_20180518_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=255)),
                ('src_pk', models.CharField(max_length=255)),
                ('dest_pk', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[(b'initiated', b'Initiated'), (b'completed', b'Completed'), (b'error', b'Error')], default=b'initiated', max_length=100)),
                ('error', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'clone',
                'verbose_name_plural': 'clones',
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='iiif_source',
            field=models.CharField(choices=[(b'images', b'Collection Images'), (b'custom', b'IIIF Manifest')], default=b'images', max_length=100),
        ),
    ]
