# Generated by Django 3.2.14 on 2022-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_service', '0010_auto_20200625_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastore',
            name='mps_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
